// Auto-generated suggested icon mappings (from scripts/icon-mapping-missing.json)
// These map effect registry IDs to likely existing icon basenames so the
// ResponsiveIcon resolution can find optimized assets without requiring file
// renames for every effect.
export const ADDITIONAL_ICON_SYNONYMS: Record<string, string> = {
  alchemist: 'alchemist',
  analysis_paralysis: 'analysis-paralysis',
  angel_investor: 'angelinvestor',
  bag_of_holding: 'bagofholding',
  ball_chain: 'ball & chain',
  beginners_luck: 'beginnersluck',
  blacksmith: 'blacksmith',
  broken_heart: 'broken heart',
  caged_bakeneko: 'caged bakeneko',
  charlatan: 'charlatan',
  clever_disguise: 'clever disguise',
  collateral_damage: 'collateral-damage',
  compound_interest: 'compoundinterest',
  counterfeiting: 'counterfeiting',
  counting_cards: 'counting cards',
  creative_accounting: 'creativeaccounting',
  destitution: 'destitution',
  diplomatic_immunity: 'diplomaticimmunity',
  doppelganger: 'doppelganger',
  endless_hunger: 'endless hunger',
  excommunication: 'excommunication',
  flesh_wound: 'flesh wound',
  fog_of_war: 'fogofwar',
  forged_signature: 'forgedsignature',
  gluttony: 'gluttony',
  golden_parachute: 'goldenparachute',
  hoarder: 'hoarder',
  hyperfixation: 'hyperfixation',
  ignorance: 'ignorance',
  impersonator: 'impersonator',
  insider_trading: 'insidertrading',
  insomnia: 'insomnia',
  jester: 'jester',
  klabautermann: 'klabautermann',
  lobbyist: 'lobbyist',
  malnourishment: 'malnourishment',
  malocchio: 'malocchio',
  martial_law: 'martiallaw',
  martyr: 'martyr',
  mood_swings: 'mood swings',
  moon_toad_cheeks: 'moontoadcheeks',
  mulligan: 'mulligan',
  nepotism: 'nepotism',
  noble_eightfold_path: 'noble eightfold path',
  offshore_account: 'offshoreaccount',
  one_armed_bandit: 'one-armed bandit',
  oracle: 'oracle',
  pedant: 'pedant',
  ponzi_scheme: 'ponzischeme',
  predatory_lending: 'predatorylending',
  quintessence: 'quintessence',
  reverse_psychology: 'reversepsychology',
  rose_colored_glasses: 'rosecoloredglasses',
  schemer: 'schemer',
  stolen_valor: 'stolenvalor',
  switcheroo: 'switcheroo',
  sycophant: 'sycophant',
  thief: 'thief',
  tortoiseshell: 'tortoiseshell',
  trickster: 'trickster',
  trust_fund: 'trustfund',
  vagrant: 'vagrant',
  weighted_dice: 'weighted dice',
  wizard: 'wizard',
};

export default ADDITIONAL_ICON_SYNONYMS;
