// Auto-generated merged icon mappings (existing + fuzzy suggestions)
// Keep this file checked in; regenerate via scripts/fuzzy-icon-mapping.cjs
export const ADDITIONAL_ICON_SYNONYMS: Record<string, string> = {
  // === Core Effects ===
  alchemist: 'alchemist',
  analysis_paralysis: 'analysis-paralysis',
  angel_investor: 'angelinvestor',
  bag_of_holding: 'bagofholding',
  bait_switch: 'baitandswitch',
  ball_chain: 'ball & chain',
  beginners_luck: 'beginnersluck',
  bifurcation: 'Bifurcation',
  blacksmith: 'blacksmith',
  broken_heart: 'broken-heart',
  butterfly_effect: 'Butterfly Effect',
  caged_bakeneko: 'caged bakeneko',
  cascading_columns: 'Cascading Columns',
  charlatan: 'charlatan',
  checkered_board: 'Checkered Board',
  clever_disguise: 'clever disguise',
  collateral_damage: 'collateral-damage',
  compound_interest: 'compoundinterest',
  cooked_books: 'Cooked Books',
  counterfeiting: 'counterfeiting',
  counting_cards: 'countingcards',
  creative_accounting: 'creativeaccounting',
  crown_of_martyr: 'Crown of Martyr',
  daruma_karma: 'duarmakarma',
  death_dishonor: 'Death & Dishonor',
  delusions_grandeur: 'delusionsofgrandeur',
  dementia: 'Dementia',
  deregulation: 'Deregulation',
  destitution: 'destitution',
  diplomatic_immunity: 'diplomaticimmunity',
  doppelganger: 'doppelganger',
  earthquake: 'Earthquake',
  eat_the_rich: 'Eat the Rich',
  emergency_reshuffle: 'Emergency Reshuffle',
  endless_hunger: 'endless hunger',
  entropy: 'Entropy',
  esrevinu_etanretla: 'Esrevinu Etanretla',
  excommunication: 'excommunication',
  flesh_wound: 'fleshwound',
  fog_of_war: 'fogofwar',
  forged_signature: 'forgedsignature',
  foundation_peek: 'Foundation Peek',
  foundation_race: 'Foundation Race',
  fountain_youth: 'fountainofyouth',
  full_house: 'Full House',
  functional_alcoholic: 'Functional Alcoholic',
  gerrymandering: 'Gerrymandering',
  get_out_of_jail_free: 'Get Out of Jail Free',
  gift_gab: 'giftofgab',
  gluttony: 'gluttony',
  golden_parachute: 'goldenparachute',
  grand_slam: 'Grand Slam',
  gravity_well: 'Gravity Well',
  herding_cats: 'Herding Cats',
  high_society: 'High Society',
  hoarder: 'hoarder',
  hostile_takeover: 'Hostile Takeover',
  hyperfixation: 'hyperfixation',
  identity_theft: 'Identity Theft',
  ignorance: 'ignorance',
  impersonator: 'impersonator',
  insider_trading: 'insidertrading',
  insomnia: 'insomnia',
  jester: 'jester',
  klabautermann: 'klabautermann',
  linked_fates: 'Linked Fates (variant)',
  lobbyist: 'lobbyist',
  lucky_sevens_wall: 'Lucky Sevens Wall',
  malnourishment: 'malnourishment',
  malocchio: 'malocchio',
  maneki_neko: 'maneki-neko',
  mandatory_minimum: 'Mandatory Minimum',
  martial_law: 'martiallaw',
  martyr: 'martyr',
  mirror_match: 'Mirror Match',
  momentum_tokens: 'Momentum Tokens',
  mood_swings: 'mood swings',
  moon_toad_cheeks: 'moontoadcheeks',
  mulligan: 'mulligan',
  mulligan_blessing: 'mulligan',
  mulligan_curse: 'mulligan',
  nepotism: 'nepotism',
  noble_eightfold_path: 'nobileeightfoldpath',
  not_gaslighting: 'Not Gaslighting',
  offshore_account: 'offshoreaccount',
  one_armed_bandit: 'one-armed bandit',
  oracle: 'oracle',
  panopticon: 'Panopticon',
  parasite_pile: 'Parasite Pile (variant)',
  path_least_resistance: 'pathofleastresistance',
  pedant: 'pedant',
  perfect_balance: 'Perfect Balance',
  phantom_tableau: 'Phantom Tableau',
  poltergeist: 'Poltergeist',
  ponzi_scheme: 'ponzischeme',
  predatory_lending: 'predatorylending',
  prick_conscience: 'prick of conscience',
  quintessence: 'quintessence',
  rainbow_bridge: 'Rainbow Bridge',
  reality_shift: 'Reality Shift',
  reverse_psychology: 'reversepsychology',
  revolving_door: 'Revolving Door',
  ritual_components: 'Ritual Components',
  rose_colored_glasses: 'rosecoloredglasses',
  royal_flush: 'Royal Flush',
  rules_of_3: '3 rules of 3',
  russian_roulette: 'Russian Roulette',
  sacred_geometry: 'Sacred Geometry',
  sacrifice_play: 'Sacrifice Play',
  schemer: 'schemer',
  schizophrenia: 'Schizophrenia',
  schrodingers_deck: 'Schrodinger\'s Deck',
  shadow_realm: 'Shadow Realm',
  shapeshifter: 'Shapeshifter',
  sleight_of_hand: 'sleightofhand',
  slush_fund: 'slushfund',
  smoke_mirrors: 'smokeandmirrors',
  solar_flare: 'Solar Flare',
  stacked_deck: 'Stacked Deck',
  stolen_valor: 'stolenvalor',
  straight_sequence: 'Straight Sequence',
  stranglehold: 'Stranglehold',
  street_smarts: 'streetsmarts',
  suit_supremacy: 'Suit Supremacy',
  sultan_of_swat: 'Sultan of Swat',
  switcheroo: 'switcheroo',
  sycophant: 'sycophant',
  synchronicity: 'synchronicity',
  tableau_swap: 'Tableau Swap',
  tableau_tiers: 'Tableau Tiers',
  tectonic_shift: 'Tectonic Shift',
  temporal_anomaly: 'Temporal Anomaly',
  the_constellation: 'The Constellation',
  thief: 'theif',
  time_rewind: 'Time Rewind',
  tortoiseshell: 'tortoiseshell',
  tower_of_power: 'Tower of Power',
  trickster: 'trickster',
  trust_fund: 'trustfund',
  uncle_timmy_boo: 'Uncle Timmy Boo',
  vagrant: 'vagrant',
  veil_uncertainty: 'Veil of Uncertainty',
  venture_capitol: 'Venture Capitol',
  weighted_dice: 'weighted dice',
  wild_card_generator: 'Wild Card Generator',
  wild_magic_surge: 'Wild Magic Surge',
  wizard: 'wizard',
  
  // === Additional icon aliases (for UI elements) ===
  card_graveyard: 'Card Graveyard',
  executive_order: 'executiveorder',
  five_finger_discount: 'fivefingerdiscount',
  kindness_of_strangers: 'kindnessofstrangers',
  legitimate_business: 'legitimatebusiness',
  liquid_assets: 'liquidassets',
  loaded_deck: 'loadeddeck',
  master_debater: 'masterdebater',
  metro_card: 'metrocard',
  midas_touch: 'midastouch',
};

export default ADDITIONAL_ICON_SYNONYMS;
